language: python

before_install:
 - sudo apt-get update

install:
 - sudo apt-get install python-dev python-numpy

before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - mvn install:install-file -Dfile=/usr/local/share/OpenCV/java/opencv-300.jar -DgroupId=opencv -DartifactId=opencv -Dversion=3.0.0 -Dpackaging=jar
  - cd ../..

python:
  - "2.7"

script:
  # We don't have Matlab on the Travis machines, so we're setting a dummy path
  # and ignoring the tests tagged for Matlab.
  - export MATLAB_LIBRARY_ROOT=/tmp
  - sbt "testOnly * -- -l MatlabTest"
  
  - python cardiganTest.py
